# .pre-commit-config.yaml
default_language_version:
  python: python3.12
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.7
  hooks:
  # Run the linter.
  - id: ruff
    types_or: [ python, pyi, jupyter ]
    args: [ --fix ]
  - id: ruff-format
    # Run the formatter.
    types_or: [ python, pyi, jupyter ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0 # Use the ref you want to point at
  hooks:
  # Simply check whether files parse as valid python.
  - id: check-ast
  - id: check-json
    # Attempts to load all json files to verify syntax.
  - id: check-yaml
    # Attempts to load all yaml files to verify syntax.
  - id: detect-private-key
    # Checks for the existence of private keys.
  - id: pretty-format-json
    # Checks that all your JSON files are pretty. "Pretty" here means that keys are sorted and indented.
    args: [ --autofix, --no-ensure-ascii ]

# # Currently excluded because we need no requirements.txt
#
# - repo: https://github.com/astral-sh/uv-pre-commit
#   rev: 0.5.16
#   hooks:
#   # Compile requirements
#   - id: pip-compile
#     args: [ --universal, pyproject.toml, -o, requirements.txt ]
#     files: ^(.*\/)?(uv\.lock|pyproject\.toml)$
