name: privacy-enabled-agents-eval

services:
  valkey:
    image: valkey/valkey:8-alpine@sha256:d827e7f7552cdee40cc7482dbae9da020f42bc47669af6f71182a4ef76a22773
    ports:
      - "6379:6379"
    volumes:
      - ./valkey-data:/data:rw
    command: ["--appendonly", "yes"] # Enable data persistence
    restart: on-failure
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - VALKEY_SAVE=60 1 # Save DB every 60 seconds if at least 1 change
    labels:
      - "com.privacy-enabled-agents.description=Valkey storage backend"

  redis:
    image: redis:8-alpine@sha256:987c376c727652f99625c7d205a1cba3cb2c53b92b0b62aade2bd48ee1593232
    ports:
      - "6380:6379"
    restart: on-failure
    labels:
      - "com.privacy-enabled-agents.description=Redis checkpointer backend"

  gliner-api:
    image: ghcr.io/freinold/gliner-api:latest
    ports:
      - "8081:8080" # API and Gradio frontend
      - "9091:9090" # Metrics endpoint
    stdin_open: true
    tty: true
    # volumes:
    #   - "${HOME}/.cache/huggingface:/app/huggingface:rw"
    #   - "./gliner-api-configs/quantized_no-entities.yaml:/app/config.yaml:ro"
    environment:
      - GLINER_API_MODEL_ID=knowledgator/gliner-x-large
      - GLINER_API_ONNX_ENABLED=True
      - GLINER_API_ONNX_MODEL_PATH=onnx/model_quantized.onnx
      - GLINER_API_DEFAULT_THRESHOLD=0.7
      - GLINER_API_DEFAULT_ENTITIES=[]

volumes:
  valkey-data:
    driver: local
