name: general
model_id: knowledgator/gliner-x-large
onnx_enabled: true
onnx_model_path: onnx/model_quantized.onnx
default_threshold: 0.5
default_entities:
- address
- age
- bank account number
- city
- country
- credit card number
- date
- date of birth
- drivers license number
- email
- health insurance number
- iban
- ip address
- license plate
- location
- passport number
- person
- phone number
- social security number
- state
- tax identification number
- vehicle identification number
- zip code
- anatomy
- bacteria
- disease
- drug
- illness
- procedure
- symptom
- test
- treatment
- virus
