name: pii
# Alternatively, there are other PII models by other authors available.
# See collection here: https://huggingface.co/collections/freinold/gliner-pii-models-68617d0735a930bacd266e8d
model_id: E3-JSI/gliner-multi-pii-domains-v1
default_threshold: 0.3
default_entities:
- address
- age
- bank account number
- city
- country
- credit card number
- date
- date of birth
- drivers license number
- email
- health insurance number
- iban
- ip address
- license plate
- location
- passport number
- person
- phone number
- social security number
- state
- tax identification number
- vehicle identification number
- zip code
